# Generated by Django 5.2.8 on 2025-11-20 14:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(max_length=100, unique=True)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('building', 'Building'), ('ready_to_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('at_customs', 'At Customs'), ('released_customs', 'Released from Customs'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='building', max_length=20)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=100, null=True)),
                ('total_weight_kg', models.FloatField(default=0.0)),
                ('items_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'international_boxes',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DomesticOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField()),
                ('status', models.CharField(choices=[('CART', 'Cart'), ('PLACED', 'Placed'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], default='CART', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domestic_orders',
            },
        ),
        migrations.CreateModel(
            name='InternationalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=50)),
                ('marketplace_order_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('order_url', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('shipped_to_warehouse', 'Shipped to Warehouse'), ('arrived_warehouse', 'Arrived at Warehouse'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='placed', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'international_orders',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('scanning_date', models.DateTimeField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('country_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('awaiting_arrival', 'Awaiting Arrival'), ('arrived_warehouse', 'Arrived at Warehouse'), ('validated', 'Validated'), ('in_box', 'In Box'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('arrived_destination_warehouse', 'Arrived at Destination Warehouse'), ('at_customs', 'At Customs'), ('released_customs', 'Released from Customs'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('mismatched', 'Mismatched')], default='awaiting_arrival', max_length=30)),
                ('condition', models.CharField(choices=[('OK', 'Ok'), ('DAMAGED', 'Damaged'), ('MISMATCHED', 'Mismatched')], default='OK', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('international_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.internationalorder')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.internationalbox')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
            ],
            options={
                'db_table': 'box_items',
            },
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.internationalbox')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.item')),
            ],
            options={
                'db_table': 'item_requests',
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.warehouse')),
            ],
            options={
                'db_table': 'lockers',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.locker'),
        ),
        migrations.CreateModel(
            name='ShipmentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_number', models.CharField(max_length=100, unique=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('international_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.internationalorder')),
            ],
            options={
                'db_table': 'shipment_labels',
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('item', 'Item'), ('box', 'Box'), ('shipment_destination', 'Shipment Destination')], max_length=20)),
                ('entity_id', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status_logs',
            },
        ),
        migrations.AddField(
            model_name='internationalbox',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.warehouse'),
        ),
        migrations.AddIndex(
            model_name='internationalorder',
            index=models.Index(fields=['customer', 'status'], name='internation_custome_eb96d7_idx'),
        ),
        migrations.AddIndex(
            model_name='internationalorder',
            index=models.Index(fields=['marketplace', 'marketplace_order_ref'], name='internation_marketp_aa75a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boxitem',
            unique_together={('box', 'item')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['customer', 'status'], name='items_custome_d87789_idx'),
        ),
        migrations.AddIndex(
            model_name='statuslog',
            index=models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='status_logs_entity__164c00_idx'),
        ),
    ]
