# Generated by Django 5.2.8 on 2025-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. 150 characters or fewer.', max_length=150, null=True, verbose_name='username'),
        ),
    ]
