# Generated by Django 5.2.8 on 2025-12-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
